[control_plane]
cp01 ansible_host=192.168.10.101 ansible_user=root
cp02 ansible_host=192.168.10.102 ansible_user=root
cp03 ansible_host=192.168.10.103 ansible_user=root

[workers]
worker01 ansible_host=192.168.10.111 ansible_user=root
worker02 ansible_host=192.168.10.112 ansible_user=root
worker03 ansible_host=192.168.10.113 ansible_user=root

[k8s:children]
control_plane
workers

[k8s:vars]
ansible_python_interpreter=/usr/bin/python3.12